import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../core/api/api_client.dart';
import '../core/api/api_endpoints.dart';
import '../data/models/share_link_model.dart';

class SharingProvider extends ChangeNotifier {
  List<ShareLinkModel> _myLinks = [];
  bool _isLoading = false;
  String? _errorMessage;

  List<ShareLinkModel> get myLinks => _myLinks;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  /// Fetch all active share links generated by user
  Future<void> fetchMyLinks() async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    final response = await ApiClient.get(ApiEndpoints.myShareLinks);
    _isLoading = false;

    if (response.success && response.data != null) {
      final List<dynamic> list = response.data is List ? response.data : [];
      _myLinks = list.map((item) => ShareLinkModel.fromJson(item)).toList();
    } else {
      _errorMessage = response.message ?? 'Failed to load share links';
    }
    notifyListeners();
  }

  /// Create a customizable share link with permissions, password, expiration
  Future<ShareLinkModel?> createShareLink({
    String? fileId,
    String? spaceId,
    String permission = 'VIEW',
    int? expiresInDays,
    int? maxDownloads,
    String? password,
  }) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    final body = <String, dynamic>{'permission': permission};
    if (fileId != null) body['fileId'] = fileId;
    if (spaceId != null) body['spaceId'] = spaceId;
    if (expiresInDays != null) body['expiresInDays'] = expiresInDays;
    if (maxDownloads != null && maxDownloads > 0) {
      body['maxDownloads'] = maxDownloads;
    }
    if (password != null && password.trim().isNotEmpty) {
      body['password'] = password.trim();
    }

    final response = await ApiClient.post(ApiEndpoints.shareLinks, body: body);
    _isLoading = false;

    if (response.success && response.data != null) {
      final newLink = ShareLinkModel.fromJson(response.data);
      _myLinks.insert(0, newLink);
      notifyListeners();
      return newLink;
    } else {
      _errorMessage = response.message ?? 'Failed to generate link';
      notifyListeners();
      return null;
    }
  }

  /// Quick 1-Tap Share: generates instant link and copies to clipboard immediately
  Future<ShareLinkModel?> quickShare({String? fileId, String? spaceId}) async {
    final link = await createShareLink(
      fileId: fileId,
      spaceId: spaceId,
      permission: 'VIEW',
      expiresInDays: 30,
    );

    if (link != null) {
      await Clipboard.setData(ClipboardData(text: link.shareUrl));
    }
    return link;
  }

  /// Revoke an active share link
  Future<bool> revokeLink(String id) async {
    final response = await ApiClient.delete(ApiEndpoints.revokeShareLink(id));
    if (response.success) {
      _myLinks.removeWhere((l) => l.id == id);
      notifyListeners();
      return true;
    }
    return false;
  }

  /// Copy link to clipboard
  Future<void> copyLink(String url) async {
    await Clipboard.setData(ClipboardData(text: url));
  }
}
